name: File Parser CI

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ 'main', 'feature/*' ]
  workflow_dispatch:

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run spotbugs check
        run: mvn clean validate spotbugs:check -Dspotbugs.report.format=xml -Dspotbugs.report.filename=target/reports/spotbugs.xml

      - name: Run PMD check
        run: mvn validate pmd:check -Dpmd.reportFormat=xml -Dpmd.outputFile=target/reports/pmd.xml

      - name: Upload PMD report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: target/reports/pmd.xml

      - name: Upload Spotbugs report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: target/reports/spotbugs.xml

  build-and-test-parser:
    strategy:
      matrix:
        java: [ 17, 21 ]
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependency
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build and run tests with coverage
        run: mvn clean verify jacoco:report -Djacoco.failOnViolation=true -Djacoco.coverageThreshold=0.8

      - name: Upload jacoco coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html